from __future__ import annotations

import os
from datetime import datetime
from typing import Dict

from utils.pdf_export import export_pdf
from utils.markdown_export import export_markdown
from utils.html_export import export_html


class ReportService:
    """Service responsible for generating downloadable reports."""

    EXPORT_FOLDER = "exports"

    @classmethod
    def ensure_export_folder(cls) -> None:
        """Create exports folder if it doesn't exist."""
        os.makedirs(cls.EXPORT_FOLDER, exist_ok=True)

    @classmethod
    def timestamp(cls) -> str:
        """Generate timestamp for filenames."""
        return datetime.now().strftime("%Y%m%d_%H%M%S")

    @classmethod
    def build_report(cls, data: Dict) -> str:
        """
        Build a Markdown report string.

        Parameters
        ----------
        data : dict
            Report content.

        Returns
        -------
        str
            Complete report text.
        """

        report = f"""# AI Video Analyzer Report

Generated : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}

---

## Video Information

**Video Name:** {data.get("video_name","N/A")}

**Provider:** {data.get("provider","N/A")}

**Model:** {data.get("model","N/A")}

---

## Transcript

{data.get("transcript","No transcript available.")}

---

## AI Analysis

{data.get("analysis","No analysis available.")}

---

## AI Chat Summary

{data.get("chat","No chat history.")}

---

Generated by AI Video Analyzer
"""

        return report

    @classmethod
    def save_markdown(cls, report: str) -> str:

        cls.ensure_export_folder()

        filename = os.path.join(
            cls.EXPORT_FOLDER,
            f"{cls.timestamp()}.md"
        )

        export_markdown(report, filename)

        return filename

    @classmethod
    def save_html(cls, report: str) -> str:

        cls.ensure_export_folder()

        filename = os.path.join(
            cls.EXPORT_FOLDER,
            f"{cls.timestamp()}.html"
        )

        export_html(report, filename)

        return filename

    @classmethod
    def save_pdf(cls, report: str) -> str:

        cls.ensure_export_folder()

        filename = os.path.join(
            cls.EXPORT_FOLDER,
            f"{cls.timestamp()}.pdf"
        )

        export_pdf(report, filename)

        return filename

    @classmethod
    def save_txt(cls, report: str) -> str:

        cls.ensure_export_folder()

        filename = os.path.join(
            cls.EXPORT_FOLDER,
            f"{cls.timestamp()}.txt"
        )

        with open(filename, "w", encoding="utf-8") as file:
            file.write(report)

        return filename

    @classmethod
    def generate_complete_report(
            cls,
            include_video: bool,
            include_audio: bool,
            include_transcript: bool,
            include_analysis: bool,
            include_chat: bool,
            include_metadata: bool,
            data: dict,
    ) -> str:
        """
        Generate a complete AI Video Analyzer report.
        """

        import json

        report = "# 🎥 AI Video Analyzer Report\n\n"

        report += f"**Generated:** {cls.timestamp()}\n\n"

        report += "---\n\n"

        ###############################################################
        # VIDEO
        ###############################################################

        if include_video:
            report += "## 📹 Video Information\n\n"

            report += f"**Filename :** {data.get('video_name', 'N/A')}\n\n"
            report += f"**Duration :** {data.get('video_duration', 'N/A')}\n\n"
            report += f"**Resolution :** {data.get('video_resolution', 'N/A')}\n\n"
            report += f"**FPS :** {data.get('video_fps', 'N/A')}\n\n"
            report += f"**Format :** {data.get('video_format', 'N/A')}\n\n"
            report += f"**Size :** {data.get('video_size', 'N/A')}\n\n"

            report += "---\n\n"

        ###############################################################
        # AUDIO
        ###############################################################

        if include_audio:
            report += "## 🎵 Audio Information\n\n"

            report += f"**Filename :** {data.get('audio_name', 'N/A')}\n\n"
            report += f"**Duration :** {data.get('audio_duration', 'N/A')}\n\n"
            report += f"**Channels :** {data.get('channels', 'N/A')}\n\n"
            report += f"**Sample Rate :** {data.get('sample_rate', 'N/A')}\n\n"
            report += f"**Format :** {data.get('audio_format', 'N/A')}\n\n"
            report += f"**Size :** {data.get('audio_size', 'N/A')}\n\n"

            report += "---\n\n"

        ###############################################################
        # TRANSCRIPT
        ###############################################################

        if include_transcript:

            report += "## 📝 Transcript\n\n"

            transcript = data.get("transcript", "")

            if transcript:
                report += str(transcript)
            else:
                report += "Transcript not available."

            report += "\n\n---\n\n"

        ###############################################################
        # AI ANALYSIS
        ###############################################################

        if include_analysis:

            report += "## 🤖 AI Analysis\n\n"

            analysis = data.get("analysis", "")

            if analysis:
                report += str(analysis)
            else:
                report += "Analysis not available."

            report += "\n\n---\n\n"

        ###############################################################
        # CHAT
        ###############################################################

        if include_chat:

            report += "## 💬 AI Chat\n\n"

            chat = data.get("chat", "")

            if isinstance(chat, (list, dict)):
                chat = json.dumps(chat, indent=4, ensure_ascii=False)

            if chat:
                report += str(chat)
            else:
                report += "Chat history not available."

            report += "\n\n---\n\n"

        ###############################################################
        # METADATA
        ###############################################################

        if include_metadata:
            report += "## ⚙ Processing Metadata\n\n"

            report += f"**Provider :** {data.get('provider', 'N/A')}\n\n"
            report += f"**Model :** {data.get('model', 'N/A')}\n\n"
            report += f"**Generated :** {cls.timestamp()}\n\n"

            report += "---\n\n"

        ###############################################################
        # END
        ###############################################################

        report += "## ✅ End of Report\n\n"

        report += "Generated by **AI Video Analyzer**."

        return report